services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TalentSphereDB
    environment:
      - MSSQL_SA_PASSWORD=TalentSphere.2024
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - TalentSphere-volume:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

networks:
  TalentSphereDB-network:
    driver: bridge

volumes:
  TalentSphere-volume:
    external: true

  TalentSphere_log-volume:
    external: true

  seq_data:
